// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// parseOutput
List parseOutput(const std::vector<std::string> file_names, const NumericVector sample_size, const int loci_number, const int program = 0, const NumericVector trio_opts = NumericVector(0));
RcppExport SEXP jaatha_parseOutput(SEXP file_namesSEXP, SEXP sample_sizeSEXP, SEXP loci_numberSEXP, SEXP programSEXP, SEXP trio_optsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const std::vector<std::string> >::type file_names(file_namesSEXP );
        Rcpp::traits::input_parameter< const NumericVector >::type sample_size(sample_sizeSEXP );
        Rcpp::traits::input_parameter< const int >::type loci_number(loci_numberSEXP );
        Rcpp::traits::input_parameter< const int >::type program(programSEXP );
        Rcpp::traits::input_parameter< const NumericVector >::type trio_opts(trio_optsSEXP );
        List __result = parseOutput(file_names, sample_size, loci_number, program, trio_opts);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// parseMsPositions
NumericVector parseMsPositions(const std::string line);
RcppExport SEXP jaatha_parseMsPositions(SEXP lineSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const std::string >::type line(lineSEXP );
        NumericVector __result = parseMsPositions(line);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// parseTrees
std::string parseTrees(const std::vector<std::string> in_files, const std::string out_file, const NumericVector trio_opts);
RcppExport SEXP jaatha_parseTrees(SEXP in_filesSEXP, SEXP out_fileSEXP, SEXP trio_optsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const std::vector<std::string> >::type in_files(in_filesSEXP );
        Rcpp::traits::input_parameter< const std::string >::type out_file(out_fileSEXP );
        Rcpp::traits::input_parameter< const NumericVector >::type trio_opts(trio_optsSEXP );
        std::string __result = parseTrees(in_files, out_file, trio_opts);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// calcPercentFpcViolation
NumericVector calcPercentFpcViolation(const NumericMatrix seg_sites, const NumericVector positions, const NumericVector trio_opts = NumericVector(0));
RcppExport SEXP jaatha_calcPercentFpcViolation(SEXP seg_sitesSEXP, SEXP positionsSEXP, SEXP trio_optsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const NumericMatrix >::type seg_sites(seg_sitesSEXP );
        Rcpp::traits::input_parameter< const NumericVector >::type positions(positionsSEXP );
        Rcpp::traits::input_parameter< const NumericVector >::type trio_opts(trio_optsSEXP );
        NumericVector __result = calcPercentFpcViolation(seg_sites, positions, trio_opts);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// calcJsfs
NumericMatrix calcJsfs(const List seg_sites, const NumericVector sample_size);
RcppExport SEXP jaatha_calcJsfs(SEXP seg_sitesSEXP, SEXP sample_sizeSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const List >::type seg_sites(seg_sitesSEXP );
        Rcpp::traits::input_parameter< const NumericVector >::type sample_size(sample_sizeSEXP );
        NumericMatrix __result = calcJsfs(seg_sites, sample_size);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// calcJsfs
NumericMatrix calcJsfs(const List seg_sites, const NumericVector sample_size);
RcppExport SEXP jaatha_calcJsfs(SEXP seg_sitesSEXP, SEXP sample_sizeSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const List >::type seg_sites(seg_sitesSEXP );
        Rcpp::traits::input_parameter< const NumericVector >::type sample_size(sample_sizeSEXP );
        NumericMatrix __result = calcJsfs(seg_sites, sample_size);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// classifyPolym
NumericVector classifyPolym(const NumericMatrix seg_sites, const NumericVector sample_size);
RcppExport SEXP jaatha_classifyPolym(SEXP seg_sitesSEXP, SEXP sample_sizeSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const NumericMatrix >::type seg_sites(seg_sitesSEXP );
        Rcpp::traits::input_parameter< const NumericVector >::type sample_size(sample_sizeSEXP );
        NumericVector __result = classifyPolym(seg_sites, sample_size);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
