# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

classifyPolym <- function(seg_sites, sample_size) {
    .Call('jaatha_classifyPolym', PACKAGE = 'jaatha', seg_sites, sample_size)
}

