# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parseMsPositions <- function(line) {
    .Call('jaatha_parseMsPositions', PACKAGE = 'jaatha', line)
}

parseMsOutput <- function(file_names, sample_size, loci_number) {
    .Call('jaatha_parseMsOutput', PACKAGE = 'jaatha', file_names, sample_size, loci_number)
}

parseSeqgenOutput <- function(file_names, sample_size, sequence_length, loci_number, trio_opts = numeric(0)) {
    .Call('jaatha_parseSeqgenOutput', PACKAGE = 'jaatha', file_names, sample_size, sequence_length, loci_number, trio_opts)
}

parseTrees <- function(in_file, trio_opts, tempfile) {
    .Call('jaatha_parseTrees', PACKAGE = 'jaatha', in_file, trio_opts, tempfile)
}

calcPercentFpcViolation <- function(seg_sites, trio_opts = numeric(0)) {
    .Call('jaatha_calcPercentFpcViolation', PACKAGE = 'jaatha', seg_sites, trio_opts)
}

#' Calculate the JSFS from a list of segregating sites statistics
#' 
#' @param seg_sites List of segregating sites
#' @param sample_size A numberic vector of size 2, giving the sample sizes
#'        of the two population for which the JSFS is calulated
#' @return The Joint Site Frequency Spectrum, as a matrix.
calcJsfs <- function(seg_sites, sample_size) {
    .Call('jaatha_calcJsfs', PACKAGE = 'jaatha', seg_sites, sample_size)
}

classifyPolym <- function(seg_sites, sample_size) {
    .Call('jaatha_classifyPolym', PACKAGE = 'jaatha', seg_sites, sample_size)
}

