# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

addToFpc <- function(seg_sites, fpc) {
    .Call('jaatha_addToFpc', PACKAGE = 'jaatha', seg_sites, fpc)
}

parseOutput <- function(file_name, sample_size, loci_number, program = 0L, generate_jsfs = TRUE, generate_seg_sites = FALSE, generate_fpc = FALSE) {
    .Call('jaatha_parseOutput', PACKAGE = 'jaatha', file_name, sample_size, loci_number, program, generate_jsfs, generate_seg_sites, generate_fpc)
}

parseMsPositions <- function(line) {
    .Call('jaatha_parseMsPositions', PACKAGE = 'jaatha', line)
}

addSegSitesToJsfs <- function(seg_sites, sample_size, jsfs) {
    .Call('jaatha_addSegSitesToJsfs', PACKAGE = 'jaatha', seg_sites, sample_size, jsfs)
}

